config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'bikes#index'
  resources :bikes,only: [:new, :create, :show,:edit,:update,:destroy] do
  resources :comments, only: :create
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
 validates :title, presence: true
 validates :catch_copy, presence: true
 validates :concept, presence: true
 validates :image, presence: true
 
 has_many :comments, dependent: :destroy
  belongs_to :user
  has_one_attached :image
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :bike

  validates :content, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
         validates :name, presence: true
         validates :profile, presence: true
         validates :my_bike, presence: true
         validates :residence, presence: true

         has_many :comments
         has_many :bikes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:profile, :my_bike, :residence])
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]

  def index
    @bikes = Bike.includes(:user)
  end

  def new
    @bike = Bike.new
  end

  def create
    @Bike = Bike.new(bike_params)
    if @Bike.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @bike.comments
  end

  def edit
  end

  def update
    if @bike.update(bike_params)
      redirect_to bike_path(@bike)
    else
      render :edit
    end
  end

  def destroy
    if @bike.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  private

  def bike_params
    params.require(:bike).permit(:title, :catch_copy, :concept, :image).merge(user_id: current_user.id)
  end

  def set_bike
    @bike = Bike.find(params[:id])
  end

  def contributor_confirmation
    redirect_to root_path unless current_user == @bike.user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to bike_path(@comment.bike)
    else
      @bike = @comment.bike
      @comments = @bike.comments
      render "bikes/show"
  end
end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, bike_id: params[:bike_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/views/bikes/_bike.html.erb
<div class="card">
  <%= link_to image_tag(bike.image, class: :card__img ), bike_path(bike) %>
  <div class="card__body">
    <%= link_to bike.title, bike_path(bike), class: :card__title%>
    <p class="card__summary">
      <%= bike.catch_copy %>
    </p>
    <%= link_to "by #{bike.user.name}", user_path(bike.user), class: :card__user %>
  </div>
</div>

app/views/bikes/_form.html.erb
<%= form_with model: bike, local: true do |f|%>
  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :catch_copy, "キャッチコピー" %><br />
    <%= f.text_area :catch_copy, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form__text %>
  </div>

  <div class="field">
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit "投稿", class: :form__btn  %>
  </div>
<% end %>

app/views/bikes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">投稿編集</h2>
      <%= render partial: "form", locals: { bike: @bike } %>
    </div>
  </div>
</div>

app/views/bikes/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        ヤエー！
        <%= link_to "#{current_user.name}さん", user_path(current_user), class: :greeting__link%>
      </div>
    <% end %>
    <div class="card__wrapper">
      <%= render partial: 'bike', collection: @bikes %>
    </div>
  </div>
</main>

app/views/bikes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規投稿</h2>
        <%= render partial: "form", locals: { bike: @bike } %>
    </div>
  </div>
</div>

app/views/bikes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="bikerspace__wrapper">
      <p class="bikerspace__hedding">
        <%= @bike.title %>
      </p>
      <%= link_to "by #{@bike.user.name}", user_path(@bike.user), class: :bikerspace__user %>
      <% if current_user == @bike.user%>
        <div class="bikerspace__manage">
          <%= link_to "編集する", edit_bike_path(@bike), class: :bikerspace__btn %>
          <%= link_to "削除する", bike_path(@bike), method: :delete, class: :bikerspace__btn %>
        </div>
      <% end %>
      <div class="bikerspace__image">
        <%= image_tag @bike.image %>
      </div>
      <div class="bikerspace__body">
        <div class="bikerspace__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @bike.catch_copy %>
          </p>
        </div>
        <div class="bikerspace__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @bike.concept %>
          </p>
        </div>
      </div>
      <div class="bikerspace__comments">
        <% if user_signed_in? %>
          <%= form_with model: [@bike, @comment], local: true do |f|%>
            <div class="field">
              <%= f.label :content, "コメント" %><br />
              <%= f.text_field :content, id:"comment_content" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %>
        <ul class="comments_lists">
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.content%>
              <%= link_to "（#{comment.user.name}）", user_path(comment.user), class: :comment_user %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> Biker Space</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
         <p style="text-align: right">
         〜バイク好きのためのSNS〜
         </p>
          </div>
            <% if user_signed_in? %>
             <div class="nav__right"> 
               <%= link_to "ログアウト", destroy_user_session_path,  method: :delete, class: :nav__logout %>
              <%= link_to "新規投稿", new_bike_path, class: :nav__btn %>
             </div> 
            <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
            <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © BIKE SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.name}"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= @user.profile %></td>
          </tr>
          <tr>
            <th class="table__col1">愛車</th>
            <td class="table__col2"><%= @user.my_bike %></td>
          </tr>
          <tr>
            <th class="table__col1">所在地</th>
            <td class="table__col2"><%= @user.residence %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.name}さんの投稿"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'bikes/bike', collection: @user.bikes %>
      </div>
    </div>
  </div>
</div>